# -*- coding: utf-8 -*-
"""Vidyax native backend (AOT): .vx -> C -> machine code.

`vidyax native prog.vx -o prog` compiles through the normal vxc pipeline
(front-end, inlining, folding, peephole, CFG passes), then translates
every proto's bytecode into a C function: one C statement sequence per
instruction, `goto` for jumps — no fetch/decode loop at runtime. The
generated file is linked against the VM's own runtime modules
(value.c, gc.c, net.c, builtins.c), so values, GC, builtins, and the ai
module are byte-for-byte the same code the VM runs.

Semantics notes (kept identical to vm.c on purpose — the differential
suite and the fuzzer compare all engines):
  - calls: same frame/slot convention; a Vidyax call is a direct C call
    through the NFN[] table, recursion depth guarded by FRAMES_MAX
  - try/catch: each `try` does setjmp in the frame that owns it;
    vm_error longjmps to the innermost handler (C callee frames just
    disappear, like the VM's nframes rewind)
  - sandbox: --allow-net / --allow-fs work; instruction/time/memory
    limits are a VM feature and are not compiled in

Known limits (documented, not bugs): no --debug/--profile (use the VM),
and `nan`/`inf` printing follows the shared fmt_double.
"""
import os
import shutil
import subprocess
import sys
import tempfile

import vidyax
from vidyax import VidyaxError
import vxc
from vxc import OPS, _OPSIZE

_OPNAME = {v: k for k, v in OPS.items()}
HERE = os.path.dirname(os.path.abspath(__file__))

PRELUDE = r"""/* generated by vidyax native — do not edit */
#ifdef VX_HAVE_CURL
#include <curl/curl.h>
#endif
#include "vx.h"

/* ---- globals (vm.c/task.c are not linked; this binary owns these) ---- */
Value  *consts;   uint32_t nconsts;
Proto  *protos;   uint32_t nprotos;
Obj    *all_objs = NULL;

/* single execution context (native `go` is Phase D) + the interpreter
 * lock the shared runtime modules expect (I/O builtins unlock around
 * their syscalls, so main() must hold it) */
static VmCtx main_ctx;
_Thread_local VmCtx *vx_ctx = NULL;
VmCtx *vx_all_ctxs = NULL;
pthread_mutex_t vx_gil = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t  vx_task_done = PTHREAD_COND_INITIALIZER;
void vx_register_ctx(VmCtx *c) { c->next = vx_all_ctxs; vx_all_ctxs = c; }
void vx_run_loop(void) {}   /* bytecode-only; never called natively */
uint64_t max_instr = 0, instr_count = 0;
size_t   max_mem = 0,  mem_used = 0;
double   max_secs = 0; clock_t start_clock;
int      allow_net = 0, allow_fs = 0;
size_t   next_gc = 1u << 20, peak_mem = 0;
int      gc_pending = 0, gc_stress = 0, gc_stats = 0;
uint64_t gc_runs = 0;

/* ---- native try/catch: one setjmp per `try`, owned by its frame ---- */
typedef struct { jmp_buf buf; int frame, saved_sp; } NTry;
static _Thread_local NTry ntry[HANDLERS_MAX];   /* per task */
static _Thread_local int  n_ntry = 0;

VX_NORETURN void vm_error(const char *fmt, ...) {
    va_list ap; va_start(ap, fmt);
    vsnprintf(errmsg, sizeof errmsg, fmt, ap);
    va_end(ap);
    if (n_ntry > 0) longjmp(ntry[n_ntry - 1].buf, 1);
    if (vx_ctx->is_task) {          /* task: record, abort to the worker */
        vx_ctx->failed = 1;
        longjmp(err_jmp, 1);        /* the runner/worker setjmp'd this */
    }
    printf("[Vidyax] %s\n", errmsg);
    exit(1);
}

/* how a V_FUNC task runs natively: call its compiled function */
static void (*NFN[])(void);
static void native_task_runner(OTask *t) {
    if (setjmp(err_jmp)) return;    /* uncaught error: failed already set */
    NFN[frames[0].proto - protos]();
    t->result = stack[sp - 1];
}

static void push(Value v) {
    if (sp >= STACK_MAX) vm_error("stack overflow");
    stack[sp++] = v;
}
static Value pop(void) { return stack[--sp]; }
#define SAFEPOINT do { if (gc_stress || gc_pending) gc(); } while (0)
"""

MAIN_TMPL = r"""
int main(int argc, char **argv) {
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--allow-net") == 0) allow_net = 1;
        else if (strcmp(argv[i], "--allow-fs") == 0) allow_fs = 1;
        else if (strcmp(argv[i], "--gc-stress") == 0) gc_stress = 1;
        else if (strcmp(argv[i], "--gc-stats") == 0) gc_stats = 1;
        else {
            fprintf(stderr, "usage: %s [--allow-net] [--allow-fs]"
                    " [--gc-stress] [--gc-stats]\n", argv[0]);
            return 1;
        }
    }
#ifdef VX_HAVE_CURL
    curl_global_init(CURL_GLOBAL_DEFAULT);
#endif
    vx_ctx = &main_ctx;
    vx_register_ctx(&main_ctx);
    vx_task_runner = native_task_runner;
    VX_LOCK();
    init_pool();
    Env *global = new_env(NULL, NULL);
    for (size_t b = 0; b < NBUILTINS; b++)
        for (uint32_t i = 0; i < nconsts; i++)
            if (consts[i].t == V_STR &&
                strcmp(AS_STR(consts[i])->chars, BUILTINS[b].name) == 0) {
                Value v; v.t = V_BUILTIN; v.as.o = (Obj *)&BUILTINS[b];
                env_set(global, AS_STR(consts[i]), v);
                break;
            }
    frames[0].proto = &protos[0];
    frames[0].ip = 0;
    frames[0].env = global;
    frames[0].base = 0;
    for (int i = 0; i < protos[0].nslots; i++)
        push(vunset());
    nframes = 1;
    np_0();
    tasks_finish();   /* join every task; report unwaited failures */
    if (gc_stats)
        fprintf(stderr, "[vxnative] gc runs: %llu, peak mem: %zu bytes\n",
                (unsigned long long)gc_runs, peak_mem);
    VX_UNLOCK();
#ifdef VX_HAVE_CURL
    curl_global_cleanup();
#endif
    return 0;
}
"""


def _cstr_lit(s):
    """A C string literal for arbitrary utf-8 text."""
    out = []
    for b in s.encode("utf-8"):
        if b in (0x22, 0x5C):            # " and backslash
            out.append("\\" + chr(b))
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def _gen_pool(c):
    """init_pool(): the constant pool + proto table as startup code."""
    L = ["static void init_pool(void) {"]
    L.append("    nconsts = %d; nprotos = %d;" % (len(c.consts), len(c.protos)))
    L.append("    consts = xmalloc(sizeof(Value) * %d);" % max(1, len(c.consts)))
    L.append("    protos = xmalloc(sizeof(Proto) * %d);" % max(1, len(c.protos)))
    for i, (kind, v) in enumerate(c.consts):
        if kind == "num":
            L.append("    consts[%d] = vnum(%r);" % (i, float(v)))
        else:
            b = v.encode("utf-8")
            L.append("    consts[%d] = vstr_o(new_str(%s, %d));"
                     % (i, _cstr_lit(v), len(b)))
    for ix, p in enumerate(c.protos):
        P = "protos[%d]" % ix
        L.append("    %s.name = AS_STR(consts[%d]);" % (P, c.cstr(p.name)))
        L.append("    %s.nparams = %d;" % (P, len(p.params)))
        L.append("    %s.params = xmalloc(sizeof(OStr *) * %d);"
                 % (P, max(1, len(p.params))))
        for j, name in enumerate(p.params):
            L.append("    %s.params[%d] = AS_STR(consts[%d]);"
                     % (P, j, c.cstr(name)))
        L.append("    %s.nslots = %d;" % (P, len(p.slots)))
        L.append("    %s.slot_names = xmalloc(sizeof(OStr *) * %d);"
                 % (P, max(1, len(p.slots))))
        for j, name in enumerate(p.slots):
            L.append("    %s.slot_names[%d] = AS_STR(consts[%d]);"
                     % (P, j, c.cstr(name)))
        L.append("    %s.nescp = %d;" % (P, len(p.esc_param_ix)))
        L.append("    %s.escp = xmalloc(%d);" % (P, max(1, len(p.esc_param_ix))))
        for j, pi in enumerate(p.esc_param_ix):
            L.append("    %s.escp[%d] = %d;" % (P, j, pi))
        L.append("    %s.ndecl = %d;" % (P, len(p.declared)))
        L.append("    %s.decl = xmalloc(sizeof(OStr *) * %d);"
                 % (P, max(1, len(p.declared))))
        for j, name in enumerate(p.declared):
            L.append("    %s.decl[%d] = AS_STR(consts[%d]);"
                     % (P, j, c.cstr(name)))
        L.append("    %s.codelen = 0; %s.code = NULL;" % (P, P))
        L.append("    %s.nlines = 0; %s.line_off = NULL; %s.line_no = NULL;"
                 % (P, P, P))
    L.append("}")
    return "\n".join(L)


def _decode(code):
    out = []
    i = 0
    while i < len(code):
        op = code[i]
        sz = _OPSIZE.get(op, 0)
        arg = int.from_bytes(code[i + 1:i + 1 + sz], "little") if sz else None
        out.append((i, op, arg, 1 + sz))
        i += 1 + sz
    return out


def _gen_proto(c, ix, p):
    """One C function per proto, mirroring vm.c's opcode semantics."""
    instrs = _decode(bytes(p.code))
    targets = set()
    back_jumps = set()
    for off, op, arg, sz in instrs:
        if _OPNAME[op] in ("JMP", "JMP_IF_FALSE", "JIF_PEEK", "JIT_PEEK",
                           "TRY_PUSH"):
            targets.add(arg)
            if arg <= off:
                back_jumps.add(off)

    L = ["static void np_%d(void) {" % ix, "    SAFEPOINT;"]
    for off, op, arg, sz in instrs:
        nm = _OPNAME[op]
        if off in targets:
            L.append("L%d:;" % off)
        e = L.append
        if nm == "CONST":
            e("    push(consts[%d]);" % arg)
        elif nm == "NULL":
            e("    push(vnull());")
        elif nm == "TRUE":
            e("    push(vbool(1));")
        elif nm == "FALSE":
            e("    push(vbool(0));")
        elif nm == "POP":
            e("    pop();")
        elif nm == "LOAD":
            e("    push(env_get(frames[nframes - 1].env, AS_STR(consts[%d])));"
              % arg)
        elif nm == "STORE":
            e("    env_set(frames[nframes - 1].env, AS_STR(consts[%d]), pop());"
              % arg)
        elif nm == "LOAD_SLOT":
            e("    { Value v = stack[frames[nframes - 1].base + %d];" % arg)
            e("      if (v.t == V_UNSET)")
            if ix == 0:
                e('          vm_error("variable \'%s\' is not defined",')
            else:
                e('          vm_error("variable \'%s\' is assigned in this '
                  'function but used before it has a value",')
            e("                   protos[%d].slot_names[%d]->chars);" % (ix, arg))
            e("      push(v); }")
        elif nm == "STORE_SLOT":
            e("    stack[frames[nframes - 1].base + %d] = pop();" % arg)
        elif nm == "ADD":
            e("    { Value b = pop(), a = pop(); push(do_add(a, b)); }")
        elif nm in ("SUB", "MUL"):
            cop = "-" if nm == "SUB" else "*"
            e("    { Value b = pop(), a = pop();")
            e("      if (!numlike(a) || !numlike(b))")
            e('          vm_error("cannot do arithmetic on %s and %s",')
            e("                   type_name(a), type_name(b));")
            e("      push(vnum(as_num(a) %s as_num(b))); }" % cop)
        elif nm == "MOD":
            e("    { Value b = pop(), a = pop();")
            e("      if (!numlike(a) || !numlike(b))")
            e('          vm_error("cannot do arithmetic on %s and %s",')
            e("                   type_name(a), type_name(b));")
            e("      double x = as_num(a), y = as_num(b);")
            e('      if (y == 0) vm_error("cannot divide by 0");')
            e("      double r = fmod(x, y);")
            e("      if (r != 0 && ((r < 0) != (y < 0))) r += y;")
            e("      push(vnum(r)); }")
        elif nm == "DIV":
            e("    { Value b = pop(), a = pop();")
            e("      if (!numlike(a) || !numlike(b))")
            e('          vm_error("cannot do arithmetic on %s and %s",')
            e("                   type_name(a), type_name(b));")
            e('      if (as_num(b) == 0) vm_error("cannot divide by 0");')
            e("      push(vnum(as_num(a) / as_num(b))); }")
        elif nm == "NEG":
            e("    { Value a = pop();")
            e('      if (!numlike(a)) vm_error("cannot negate %s", type_name(a));')
            e("      push(vnum(-as_num(a))); }")
        elif nm in ("EQ", "NE"):
            bang = "" if nm == "EQ" else "!"
            e("    { Value b = pop(), a = pop(); "
              "push(vbool(%svalues_eq(a, b))); }" % bang)
        elif nm in ("LT", "LE", "GT", "GE"):
            cop = {"LT": "<", "LE": "<=", "GT": ">", "GE": ">="}[nm]
            e("    { Value b = pop(), a = pop(); "
              "push(vbool(values_cmp(a, b) %s 0)); }" % cop)
        elif nm == "NOT":
            e("    push(vbool(!truthy(pop())));")
        elif nm == "JMP":
            if arg <= off:
                e("    SAFEPOINT;")
            e("    goto L%d;" % arg)
        elif nm == "JMP_IF_FALSE":
            if arg <= off:
                e("    SAFEPOINT;")
            e("    if (!truthy(pop())) goto L%d;" % arg)
        elif nm == "JIF_PEEK":
            e("    if (!truthy(stack[sp - 1])) goto L%d;" % arg)
        elif nm == "JIT_PEEK":
            e("    if (truthy(stack[sp - 1])) goto L%d;" % arg)
        elif nm == "LIST":
            e("    { OList *l = new_list(%d);" % max(1, arg))
            e("      for (int i = 0; i < %d; i++) "
              "list_push(l, stack[sp - %d + i]);" % (arg, arg))
            e("      sp -= %d; push(vlist_o(l)); }" % arg)
        elif nm == "INDEX":
            e("    { Value i = pop(), o = pop(); push(do_index(o, i)); }")
        elif nm == "CALL":
            e("    { Value callee = stack[sp - %d - 1];" % arg)
            e("      if (callee.t == V_BUILTIN) {")
            e("          Value r = ((Builtin *)callee.as.o)->fn(%d, "
              "&stack[sp - %d]);" % (arg, arg))
            e("          sp -= %d + 1; push(r);" % arg)
            e("      } else if (callee.t == V_BOUND) {")
            e("          OBound *bm = AS_BOUND(callee);")
            e("          Value r = ai_invoke(bm->self, bm->method, %d, "
              "&stack[sp - %d]);" % (arg, arg))
            e("          sp -= %d + 1; push(r);" % arg)
            e("      } else if (callee.t == V_FUNC) {")
            e("          OFunc *fn = AS_FUNC(callee);")
            e("          Proto *pr = fn->proto;")
            e("          if (%d != pr->nparams)" % arg)
            e('              vm_error("function \'%s\' needs %d args, got %d",')
            e("                       pr->name->chars, pr->nparams, %d);" % arg)
            e('          if (nframes >= FRAMES_MAX) vm_error("recursion too deep");')
            e("          int base = sp - %d - 1;" % arg)
            e("          memmove(&stack[base], &stack[base + 1], "
              "(size_t)%d * sizeof(Value));" % arg)
            e("          sp = base + %d;" % arg)
            e("          for (int i = %d; i < pr->nslots; i++) push(vunset());"
              % arg)
            e("          Env *env;")
            e("          if (pr->nescp > 0 || pr->ndecl > 0) {")
            e("              env = new_env(fn->closure, pr);")
            e("              for (int k = 0; k < pr->nescp; k++) {")
            e("                  int pi = pr->escp[k];")
            e("                  env_set(env, pr->params[pi], stack[base + pi]);")
            e("              }")
            e("          } else env = fn->closure;")
            e("          frames[nframes].proto = pr;")
            e("          frames[nframes].ip = 0;")
            e("          frames[nframes].env = env;")
            e("          frames[nframes].base = base;")
            e("          nframes++;")
            e("          NFN[pr - protos]();")
            e("      } else {")
            e('          vm_error("this is not a function");')
            e("      } }")
        elif nm == "MAKE_FUNC":
            e("    { OFunc *fn = (OFunc *)alloc_obj(sizeof(OFunc), O_FUNC);")
            e("      fn->proto = &protos[%d];" % arg)
            e("      fn->closure = frames[nframes - 1].env;")
            e("      Value v; v.t = V_FUNC; v.as.o = (Obj *)fn; push(v); }")
        elif nm == "AI_NEW":
            e("    push(vai_o(new_ai()));")
        elif nm == "GET_MEMBER":
            e("    { Value obj = pop(); "
              "push(member_get(obj, AS_STR(consts[%d]))); }" % arg)
        elif nm == "RET":
            e("    { while (n_ntry > 0 && ntry[n_ntry - 1].frame == nframes - 1)")
            e("          n_ntry--;")
            e("      Value r = pop();")
            e("      sp = frames[nframes - 1].base;")
            e("      nframes--;")
            e("      push(r);")
            e("      return; }")
        elif nm == "PRINT":
            e("    { OStr *s = vstr(pop());")
            e("      fwrite(s->chars, 1, s->len, stdout); "
              "fputc('\\n', stdout); }")
        elif nm == "ASK":
            e("    { OStr *prompt = vstr(pop());")
            e("      fwrite(prompt->chars, 1, prompt->len, stdout);")
            e("      fputc(' ', stdout); fflush(stdout);")
            e("      char *line = NULL; size_t cap = 0;")
            e("      ssize_t n = getline(&line, &cap, stdin);")
            e('      if (n < 0) { free(line); vm_error("input ended"); }')
            e("      while (n > 0 && (line[n-1] == '\\n' || line[n-1] == '\\r')) n--;")
            e("      push(vstr_o(new_str(line, (uint32_t)n)));")
            e("      free(line); }")
        elif nm == "CHECK_RPT":
            e("    { Value v = stack[sp - 1];")
            e('      if (v.t != V_NUM) vm_error("\'rpt\' needs a number");')
            e("      stack[sp - 1] = vnum(trunc(v.as.n)); }")
        elif nm == "CHECK_ITER":
            e("    { Value v = stack[sp - 1];")
            e("      if (v.t != V_LIST && v.t != V_STR)")
            e('          vm_error("\'for ... in\' needs a list or text"); }')
        elif nm == "LEN":
            e("    { Value v = pop();")
            e("      push(vnum(v.t == V_LIST ? (double)AS_LIST(v)->count")
            e("                              : (double)AS_STR(v)->len)); }")
        elif nm == "TRY_PUSH":
            e('    { if (n_ntry >= HANDLERS_MAX) vm_error("too many nested try");')
            e("      volatile int my = n_ntry;")
            e("      NTry *h = &ntry[n_ntry++];")
            e("      h->frame = nframes - 1; h->saved_sp = sp;")
            e("      if (setjmp(h->buf)) {")
            e("          n_ntry = my;")
            e("          nframes = ntry[my].frame + 1;")
            e("          sp = ntry[my].saved_sp;")
            e("          push(vstr_o(new_str(errmsg, (uint32_t)strlen(errmsg))));")
            e("          goto L%d;" % arg)
            e("      } }")
        elif nm == "GO":
            e("    task_spawn(%d);" % arg)
        elif nm == "TRY_POP":
            e("    n_ntry--;")
        elif nm == "HALT":
            e("    return;")
        else:
            raise VidyaxError("native: unsupported opcode %s" % nm)
    L.append("}")
    return "\n".join(L)


def emit_c(c):
    parts = [PRELUDE]
    parts.append("\n".join("static void np_%d(void);" % i
                           for i in range(len(c.protos))))
    parts.append("static void (*NFN[])(void) = { %s };"
                 % ", ".join("np_%d" % i for i in range(len(c.protos))))
    parts.append(_gen_pool(c))
    for ix, p in enumerate(c.protos):
        parts.append(_gen_proto(c, ix, p))
    parts.append(MAIN_TMPL)
    return "\n\n".join(parts) + "\n"


def native_file(path, out=None, keep_c=False):
    with open(path, encoding="utf-8") as f:
        c = vxc.compile_source(f.read(),
                               os.path.dirname(os.path.abspath(path)))
    c.serialize()          # runs peephole + CFG passes and interns names
    csrc = emit_c(c)
    out = out or os.path.splitext(path)[0]
    vmdir = os.path.join(HERE, "vm")
    mods = [os.path.join(vmdir, m)
            for m in ("value.c", "gc.c", "net.c", "builtins.c", "task.c")]
    cc = os.environ.get("CC", "cc")
    curl = shutil.which("pkg-config") and subprocess.run(
        ["pkg-config", "--exists", "libcurl"]).returncode == 0
    cfile = out + ".native.c" if keep_c else None
    with tempfile.TemporaryDirectory() as td:
        if cfile is None:
            cfile = os.path.join(td, "gen.c")
        with open(cfile, "w") as f:
            f.write(csrc)
        cmd = [cc, "-O2", "-I", vmdir, cfile, *mods, "-o", out, "-lm", "-lpthread"]
        if curl:
            flags = subprocess.run(["pkg-config", "--cflags", "--libs",
                                    "libcurl"], capture_output=True,
                                   text=True).stdout.split()
            cmd = ([cc, "-O2", "-DVX_HAVE_CURL", "-I", vmdir, cfile, *mods,
                    "-o", out, "-lm", "-lpthread"] + flags)
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            raise VidyaxError("native compilation failed:\n" + r.stderr[:2000])
    return out
